### ISSUE TITLE
Linux source build for 3.5.4 branch broken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yuri-moens/eid-mw#42]
```
What steps will reproduce the problem?
1. Download latest sources from the 3.5.4 branch.
2. Run ./configure and make
3. The build process will halt with the following message:
make[1]: *** [mainwnd.o] Error 1
In file included from moc_mainwnd.cpp:10:
mainwnd.h:394: error: 'BOOL' does not name a type\
make[1]: *** [moc_mainwnd.o] Error 1
make[1]: Leaving directory 
`/var/tmp/portage/app-misc/beid-runtime-3.5.4/work/beid-runtime-3.5.4/eid-mw/_sr
c/eidmw/eidgui'

What is the expected output? What do you see instead?
The build should complete successfully.

What version of the product are you using? On what operating system?
Gentoo Linux, latest ebuild from http://bugs.gentoo.org/show_bug.cgi?id=187422

Please provide any additional information below.
Issue is caused by commits of Windows-only code in revision 382 and 385.
```

Original issue reported on code.google.com by `albert.t...@gmail.com` on 26 Jun 2010 at 12:05
